version: '3.7'

services:
  postgres:
    container_name: postgres_p1
    image: postgres
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pichau
    ports:
      - "5432:5432"
    volumes:
      - type: volume 
        source: postgres_data
        target: /var/lib/postgresql/postgres_data
      - type: bind 
        source: ./init_db/bash_init.sh
        target: /docker-entrypoint-initdb.d/bash_init.sh
    networks:
      - pichaunet
  
  pgadmin:
    container_name: pgadmin_p3
    image: dpage/pgadmin4:6.6
    restart: "no"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - pichaunet
  
  fastapi:
    container_name: fastapi_p2
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - postgres
    command: sh -c "python pichau_scraping.py && python -m uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    networks:
      - pichaunet

networks:
  pichaunet:
    driver: bridge

volumes:
  postgres_data: